networks:
  demo-server:
    driver: bridge

version: '3.7'
services:
  ## PostgresSQL Docker Compose Config
  postgres-user:
    image: postgres
    container_name: postgres-user
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=demo-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=husan
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - demo-server

  demo-server:
    image: demo-server:latest
    container_name: demo-server
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-user:5432/demo-server
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - postgres-user
    networks:
      - demo-server

volumes:
  postgres-data: