server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://128.199.3.217:5432/demo-server
    username: postgres
    password: husan
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect